# Generated by Django 3.1.3 on 2023-08-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230812_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='correct',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='course_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='choice',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grading',
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=5),
        ),
    ]
